config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"

  resources :raclettes do
    resources :bookings, except: [:destroy]
  end

  resources :bookings, only: [] do
    resources :reviews, except: [:destroy]
    member do # crée une route custom inside bookings
      patch :accepted
      patch :declined
      patch :canceled
    end
  end
  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :raclette
  has_many :reviews

  validates :date, presence: true
  validates :description, presence: true
  validates :small_eater, numericality: { greater_than_or_equal_to: 0 }
  validates :normal_eater, numericality: { greater_than_or_equal_to: 0 }
  validates :big_eater, numericality: { greater_than_or_equal_to: 0 }
  validates :veggies, numericality: { greater_than_or_equal_to: 0 }
  validates :status, acceptance: { accept: ['pending', 'accepted', 'declined', 'canceled'] }
  scope :pending, -> { where(status: "pending") }
  scope :accepted, -> { where(status: "accepted") }
  scope :declined, -> { where(status: "declined") }
  # validate :sum_eater

  # def sum_eater
  #   eaters = (small_eater + normal_eater + big_eater + veggies)
  #   if eaters > raclette.number_of_guests || eaters == 0
  #     errors.add(:base, 'sum of the eaters must be lower or equal to the number of possible guests for the event')
  #   end
  # end
end

app/models/raclette.rb
class Raclette < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :location, presence: true
  validates :title, presence: true

  validates :number_of_guests, presence: true
  validates :photo, presence: true

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_location,
                  against: %i[location],
                  using: { tsearch: { prefix: true } }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user

  validates :rating, presence: true, numericality: { in: 0..5 }
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_one_attached :avatar
  has_many :raclettes
  has_many :bookings
  has_many :requests, through: :raclettes, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_raclette, only: %i[new create edit update destroy show]
  before_action :set_booking, only: %i[edit update show accepted declined canceled]

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(params_booking)
    @booking.user = current_user
    @booking.raclette = @raclette
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
      flash.alert = "Booking added."
    else
      flash.alert = "Please verify all inputs"
      render "raclettes/show", status: :unprocessable_entity
    end
  end

  def index
    @bookings = policy_scope(Booking)
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    @booking.update(params_booking)
    redirect_to raclette_booking_path(@raclette, @booking)
  end

  def show
    authorize @booking
  end

  def canceled
    authorize @booking
    if @booking.update(status: "canceled")
      redirect_to dashboard_path, status: :see_other
    end
  end

  def accepted
    authorize @booking
    if @booking.update(status: "accepted")
      redirect_to dashboard_path
    end
  end

  def declined
    authorize @booking
    if @booking.update(status: "declined")
      redirect_to dashboard_path
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_raclette
    @raclette = Raclette.find(params[:raclette_id])
  end

  def params_booking
    params.require(:booking).permit(:date, :description, :raclette_id, :status, :big_eater, :normal_eater, :small_eater, :veggies)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @review = Review.new
  end
end

app/controllers/raclettes_controller.rb
class RaclettesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_raclette, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @raclettes = policy_scope(Raclette).near(params[:query], 10)

    else
      @raclettes = policy_scope(Raclette)
    end
    @markers = @raclettes.geocoded.map do |raclette|
      {
        lat: raclette.latitude,
        lng: raclette.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: {raclette: raclette}),
        image_url: helpers.asset_url("fromage.svg")
      }
    end
  end

  def show
    authorize @raclette
    @booking = Booking.new
  end

  def new
    @raclette = Raclette.new
    authorize @raclette
  end

  def create
    @raclette = Raclette.new(params_raclette)
    @raclette.user = current_user
    authorize @raclette
    if @raclette.save
      redirect_to raclette_path(@raclette)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @raclette
  end

  def update
    authorize @raclette
    @raclette.update(params_raclette)
    redirect_to raclette_path(@raclette)
  end

  def destroy
    authorize @raclette
    @raclette.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def set_raclette
    @raclette = Raclette.find(params[:id])
  end

  def params_raclette
    params.require(:raclette).permit(:location, :photo, :title, :description, :number_of_guests)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create edit update]
  before_action :set_review, only: %i[edit update]

  def new
    @review = Review.new(booking_id: @booking.id)
    authorize @review
  end

  def create
    @review = Review.new(params_review)
    @review.user = current_user
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to raclette_path(@booking.raclette)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @review
  end

  def update
    authorize @review
    @review.update(params_review)
    redirect_to raclette_path(@booking.raclette)
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def params_review
    params.require(:review).permit(:description, :rating, :booking_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@raclette, @booking],
                          html: {
                            data: {
                              controller: 'flatpickr'
                          }
                    } do |f| %>
      <%= f.input :date,
              as: :string,
              input_html: {
                data: {
                  flatpickr_target: 'startDateInput',
              },
                :placeholder => "Pick a date" } %>
      <%= f.input :description, :input_html => { :placeholder => "Tell #{@raclette.user.first_name} what's your plan" } %>
      <%= f.input :big_eater, :input_html => { :min => 0 }%>
      <%= f.input :normal_eater, :input_html => { :min => 0 } %>
      <%= f.input :small_eater, :input_html => { :min => 0 } %>
      <%= f.input :veggies, :input_html => { :min => 0 } %>
      <%= f.button :submit, class: "main-button w-100" %>
    <% end %>

app/views/bookings/edit.html.erb
<h1> Modifier votre raclette </h1>
<%= render "bookings/form", booking: @booking, raclette: @raclette  %>
<%# <%= simple_form_for [@raclette, @booking] do |f| %>
<%#
  <%= f.input :date %>
  <%# <%= f.input :description %> 
  <%# <%= f.input :status, collection: ["confirmed", "declined"] %>
  <%# <%= f.submit %>
<%# <% end %>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaRaclette</title>
    <link rel="icon" type="image/png" href="/images/favicon.png"/>
    <link rel="shortcut icon" type="image/png" href="/images/logo.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://www.marciatack.fr/wp-content/uploads/2021/01/raclette-fromage-1-sur-1.jpg')">
  <%# <%= form_with url: raclettes_path, method: :get, class: "d-flex" do %>
        <%# <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a raclette"
        %>
        <%# <%= submit_tag "Search", class: "secondary-button" %>
      <%# <% end %>
  <%# <div class="container">
    <div class="card-banner">

        <h1>Ma Raclette</h1>
        <p>Say cheese!</p>

      <div class="card-banner-logo">
        <img src="https://upload.wikimedia.org/wikipedia/fr/thumb/9/9a/Logo_D%C3%A9partement_Savoie.svg/695px-Logo_D%C3%A9partement_Savoie.svg.png?20180409184647" alt="Savoie's Logo">
      </div>
      <div class="card-banner-cta">
        <%= link_to "Find a raclette now!", raclettes_path, class: "main-button" %>
        <div class="card-banner">
        <p>On va en faire tout un fromage!</p>
        </div>
        <div class="container search_banner">
        <%= form_with url: raclettes_path, method: :get, class: "d-flex form-search" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Type an address"
        %>
        <%= submit_tag "Search", class: "secondary-button" %>
      <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
<div class="container mt-5 mb-5">
  <h2>Browse some of the last added raclettes 🧀</h2>
  <div class="cards-grid-home">
    <% Raclette.last(5).reverse.each do |raclette| %>
      <%= link_to raclette_path(raclette) do %>
        <div class="card-grid-home" >
          <%=cl_image_tag raclette.photo.key %>
          <h2><%= raclette.title %></h2>
          <p><i class="fa-solid fa-location-pin"></i> <%= raclette.location %></p>
          <p><i class="fa-solid fa-person"></i> <i class="fa-solid fa-person-dress"></i> <%= raclette.number_of_guests %> persons allowed</p>
        </div>
          <%# <><%= raclette.title %>
          <%# <><%= raclette.photo %>
          <%# <><%= raclette.location %>
          <%# <><%= raclette.number_of_guests %>
          <%# <><%= raclette.description %>
          <%# <><%= raclette.user.avatar %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/raclettes/_form.html.erb
<%= simple_form_for(raclette) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :location,
    input_html: {data: {location_autocomplete_target: "location"}, class: "d-none"},
    wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <%= f.input :photo, as: :file   %>
    <%= f.submit %>
<% end %>

app/views/raclettes/_info_window.html.erb
  <%= link_to raclette_path(raclette) do %>
    <div>
      <%= cl_image_tag raclette.photo.key, crop: :fill %>
      <h2><%= raclette.title %></h2>
      <p><%= raclette.location %></p>
    </div>
  <% end %>

app/views/raclettes/edit.html.erb
<div class="container">
  <h1>Edit <%= @raclette.title %></h1>
  <%= render "form", raclette: @raclette %>
</div>

app/views/raclettes/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.manigod.com/medias/images/prestataires/raclette-party-13162.jpg);">
  <div class="container">
  <h1>Find the hottest raclettes in your region</h1>
  </div>
</div>
<div class="container d-flex mt-5">
  <div class="half-container">
    <div class="cards-grid-index" >
      <% @raclettes.each do |raclette| %>
        <%= link_to raclette_path(raclette) do%>
          <div class="card-grid-index">
            <%= image_tag raclette.photo %>
            <div class="card-product-infos">
            <h2><%= raclette.title %></h2>
            <p><i class="fa-solid fa-location-pin"></i> <%= raclette.location %></p>
            <p><i class="fa-solid fa-person"></i> <i class="fa-solid fa-person-dress"></i> <%= raclette.number_of_guests %> persons allowed</p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

   <div class="half-container map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/raclettes/new.html.erb
<div class="container col-4 offset-4 mt-5 mb-5">
  <h1>Create a new raclette</h1>
  <%= render "form", raclette: @raclette  %>
</div>

app/views/raclettes/show.html.erb
<div class="container">
  <div class="raclette-infos">
    <div class="raclette-infos-title">
    <h1><%= @raclette.title %></h1>
    </div>
    <div class="raclette-infos-subtitle">
      <p> hosted by <%= @raclette.user.first_name %> <%= @raclette.user.last_name %>
      <i class="fa-solid fa-location-pin"></i> <%= @raclette.location %></p>
      <!--  ********** UNLESS TEST IF EMPTY REVIEWS  **********  -->
      <% unless @raclette.reviews.empty? %>
        <p><i class="fa-solid fa-star"></i>
        <% sum = 0  %>
        <% @raclette.reviews.each do |review| %>
          <% sum += review.rating %>
          <% end %>
        <% sum /= @raclette.reviews.all.count %>
        <%= sum.truncate(2) %> • <button class="modal-button" data-bs-toggle="modal" data-bs-target="#reviewsModal"><%= @raclette.reviews.all.count %> comments</button>
        <!--  **********  MODAL REVIEW  **********  -->
        <div class="modal fade" id="reviewsModal" tabindex="-1" aria-labelledby="reviewsModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="reviewsModalLabel"><%= @raclette.title %>'s reviews</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <% @raclette.reviews.each do |review| %>
                  <div class="review-box">
                    <i class="fa-solid fa-star"></i> <%= review.rating %> from <%= review.user.first_name %>
                    <br>
                    <%= review.description %>
                    <br>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <!--  ********** END OF MODAL REVIEW  **********  -->
        </p>
      <% end %> <!--  ********** END OF UNLESS STATEMENT  **********  -->
    </div>
  </div>
</div>
<div class="container d-flex justify-content-between">

  <%# <div class="raclette-images"> %>
    <div class="raclette-images-picture me-3">
      <% if @raclette.photo.attached? %>
      <%= cl_image_tag @raclette.photo.key %>
    <% end %>
    <div class="raclette-content">
    <div class="raclette-content-description">
      <div class="description">
        <h5>What's to expect?</h5>
        <p><%= @raclette.description %></p>
      </div>
      <div class="description">
      <h5>How many guests are expected?</h5>
      <p><%= @raclette.number_of_guests %></p>
      </div>
      <div class="description">
        <h5>Types of cheese</h5>
        <ul>
          <li>Morbier</li>
          <li>Raclette au piment d'espelette</li>
          <li>Raclette au lait cru</li>
          <li>Raclette au 3 poivres</li>
        </ul>
      </div>
      <div class="description">
        <h5>meat & alternatives</h5>
          <ul>
            <li>jambon blanc</li>
            <li>Jambon cru</li>
            <li>Rosette</li>
            <li>grison</li>
            <li>carottes</li>
            <li>salade</li>
          </ul>
      </div>
      <div>
      </div>

    </div>
    <%# <div class="raclette-content-booking">
      <h3 class="text-center">Book this raclette!</h3>
       <%= render "bookings/form", booking: @booking, raclette: @raclette  %>
    <%# </div> %>
  </div>
    </div>
    <%# <div class="raclette-images-map"></div> %>
  <%# </div> %>
  <div class="raclette-content-booking">
    <h3 class="text-center">Book this raclette!</h3>
    <%= render "bookings/form", booking: @booking, raclette: @raclette  %>
  </div>

</div>

app/views/reviews/edit.html.erb
<div class="container">
  <h1>Edit <%= @booking.description %></h1>

<%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :description %>
    <%= f.input :rating %>
    <%= f.submit %>
<% end %>
</div>

app/views/reviews/new.html.erb
<h1><%= @booking.description  %></h1>

<%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :description %>
    <%= f.input :rating %>
    <%= f.submit %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
  <%= link_to root_path do %>

    <img  class="logo" src="https://res.cloudinary.com/dxdnj4zbo/image/upload/v1669387302/Blanc_et_Cercle_Rouge_Art_Logo_2_eracyy.png">

  <% end %>

    <%# <%= link_to <img src="https://upload.wikimedia.org/wikipedia/fr/thumb/9/9a/Logo_D%C3%A9partement_Savoie.svg/695px-Logo_D%C3%A9partement_Savoie.svg.png?20180409184647">, root_path , class: "navbar-brand" %>
    <div class="d-flex" >
    <% unless params[:action] == "index" && params[:controller] == "raclettes" || params[:action] == "home" %>
      <%= form_with url: raclettes_path, method: :get, class: "d-flex form-search" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Type an address"
        %>
        <%= submit_tag "Search", class: "secondary-button" %>
      <% end %>
    <% end %>
      <%= link_to "Add A Raclette", new_raclette_path, class: "btn btn-navbar" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
               <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %> <%# à completer quand le dashboard sera fait  %>
               <%= link_to "My settings", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete},
               class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    </div>
  </div>
</div>